name: Add Publisher to environment

on:
  workflow_dispatch:
    inputs:

      environment-url:
        description: URL to import the Publisher solution into 
        required: false

      # environment:
      #   description: 'or existing Environment to  import the Publisher solution into'
      #   type: environment
      #   required: false

jobs:
  build-publisher:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: build/packed/taco_publisher.zip
          solution-folder: solutions/taco_publisher/src
          solution-type: Unmanaged

      - uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          solution-file: build/packed/taco_publisher.zip
          environment-url:  "${{ inputs.environment-url }}"
          tenant-id: "${{ secrets.APP_TENANT_ID }}"
          app-id: "${{ secrets.APP_ID }}"
          client-secret: "${{ secrets.APP_SECRET }}"          

      - uses: actions/upload-artifact@v2
        with:
          name: packed-solutions
          path: build/packed


  # deploy:
  #   runs-on: ubuntu-latest
  #   if:  ${{ inputs.environment-url }} 

  #   needs:
  #     - build-publisher
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: packed-solutions

  #     - uses: microsoft/powerplatform-actions/import-solution@v0
  #       with:
  #         solution-file: taco_publisher.zip
  #         environment-url:  "${{ inputs.environment-url }}"
  #         tenant-id: "${{ secrets.APP_TENANT_ID }}"
  #         app-id: "${{ secrets.APP_ID }}"
  #         client-secret: "${{ secrets.APP_SECRET }}"
  #         # environment-url:  "${{ secrets.CSD_ENVIRONMENT_URL }}"