name: commit-solution
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Commit message'
        required: true 
        default: '.'
        type: string

      environment:
        description: 'Environment to extract solution from'
        type: environment
        required: true 

      solution:
        description: 'solution to extract and commit'
        required: true
        default: 'TeamsAACQOrchestrator' 
        type: choice
        options:
        - TeamsAACQOrchestrator
        - taco_publisher

      solution_type:
        description: 'Export Both or only Unmanaged'
        required: true 
        default: 'Both' 
        type: choice
        options:
        - Both
        - Unmanaged


jobs:
  commit:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    if:  ${{ inputs.message }} 
    steps:
      - name: Print intent
        run: 
          echo Export ${{ inputs.solution }} from ${{ inputs.environment }}
          echo as a ${{ inputs.solution_type }} solution
          echo with message ${{ inputs.message }}


      - name: Ping environment ${{ inputs.environment }}
        id: ping
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          environment-url:  "${{ secrets.CDSENVIRONMENTURL }}"
          tenant-id: "${{ secrets.TENANTID }}"
          app-id: "${{ secrets.CLIENTID }}"
          client-secret: "${{ secrets.CLIENTSECRET }}"


      - run: echo ${{ steps.ping.ouputs.environment-id}}

      # - name: Extract solution

      # - name: Commit solution
      # - name: Push solution
      