name: commit-solution
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Commit message'
        required: true 
        type: string

      environment:
        description: 'Environment to extract solution from'
        type: environment
        required: true 

      solution:
        description: 'solution to extract and commit'
        required: true
        default: 'TeamsAACQOrchestrator' 
        type: choice
        options:
        - TeamsAACQOrchestrator
        - taco_publisher

      solution_type:
        description: 'Export Both or only Unmanaged'
        required: true 
        default: 'Both' 
        type: choice
        options:
        - Both
        - Unmanaged


jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.message }} 
    steps:
      - name: Print intent
        run: 
          echo Export ${{ inputs.solution }} from ${{ inputs.environment }}
          echo as a ${{ inputs.solution_type }} solution
          echo with message ${{ inputs.message }}

      - name: Ping environment ${{ inputs.environment }}
        run: echo ${{ secrets.CDSENVIRONMENTURL }}
        
      - run: echo ${{ secrets.TENANTID }}
      - run: echo ${{ secrets.CLIENTID }}
      - run: echo ${{ secrets.CLIENTSECRET }}
    

      # - name: Extract solution

      # - name: Commit solution
      # - name: Push solution
      