name: commit-solution
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Commit message'
        required: true 
        default: '.'
        type: string

      environment:
        description: 'Environment to extract solution from'
        type: environment
        required: true 

      solution_name:
        description: 'solution to extract and commit'
        required: true
        default: 'TeamsAACQOrchestrator' 
        type: choice
        options:
        - TeamsAACQOrchestrator
        - taco_publisher

      solution_type:
        description: 'Export Both or only Unmanaged'
        required: true 
        default: 'Both' 
        type: choice
        options:
        - Both
        - Unmanaged


jobs:
  commit:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    if:  ${{ inputs.message }} 
    steps:
      - uses: actions/checkout@v2
        # us GH Personal Access Token to allow other actions to trigger on any changes to the repo
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - run: echo Export ${{ inputs.solution_name }} from ${{ inputs.environment }}

      - name: Ping environment ${{ inputs.environment }}
        id: ping
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          environment-url:  "${{ secrets.CDSENVIRONMENTURL }}"
          tenant-id: "${{ secrets.TENANTID }}"
          app-id: "${{ secrets.CLIENTID }}"
          client-secret: "${{ secrets.CLIENTSECRET }}"

      - run: echo Connected to Environment ID ${{ steps.ping.outputs.environment-id}}

      - uses: ./.github/actions/export-unpack-commit
        with:
          solution-name: ${{ inputs.solution_name }}
          message: ${{ inputs.message }}
          environment-url:  "${{ secrets.CDSENVIRONMENTURL }}"
          tenant-id: "${{ secrets.TENANTID }}"
          app-id: "${{ secrets.CLIENTID }}"
          client-secret: "${{ secrets.CLIENTSECRET }}"
